CF_FIRST = 0
CF_2 = 1
CF_3 = 2
DH_FIRST = 3
DH_2 = 4
DH_3 = 5
DH_4 = 6
DH_5 = 7
DH_6 = 8
ECL_FIRST = 9
ECL_2 = 10
ECL_3 = 11
GZ_FIRST = 12
GZ_2 = 13
GZ_3 = 14
GZ_4 = 15
GZ_5 = 16
JF_FIRST = 17
JF_2 = 18
JF_3 = 19
JF_4 = 20
JF_5 = 21
JF_6 = 22
MB_FIRST = 23
MB_2 = 24
P_FIRST = 25
P_2 = 26
P_3 = 27
P_4 = 28
P_5 = 29
P_6 = 30
P_7 = 31
POW_FIRST = 32
POW_2 = 33
POW_3 = 34
POW_4 = 35
BC_FIRST = 36
BC_2 = 37
BC_3 = 38
BC_4 = 39
BC_5 = 40
BC_6 = 41
DC_FIRST = 42
DC_2 = 43
RV_FIRST = 44
RV_2 = 45
SPR_FIRST = 46
SPR_2 = 47
BEAR_FIRST = 48
BEAR_2 = 49
CT_FIRST = 50
CT_2 = 51
CFF_FIRST = 52
CFF_2 = 53
DOD_FIRST = 54
MILK_FIRST = 55
OLD_FIRST = 56
OLD_2 = 57
MF_FIRST = 58
MF_2 = 59
MM_FIRST = 60
MM_2 = 61
RF_FIRST = 62
RF_2 = 63
SG_FIRST = 64
SG_2 = 65
FC_FIRST = 66
FC_2 = 67
FC_3 = 68
FC_4 = 69

TYPE_CF = 0
TYPE_DH = 1
TYPE_ECL = 2
TYPE_GZ = 3
TYPE_JF = 4
TYPE_MB = 5
TYPE_P = 6
TYPE_POW = 7
TYPE_BC = 8
TYPE_DC = 9
TYPE_RV = 10
TYPE_SPR = 11
TYPE_BEAR = 12
TYPE_CT = 13
TYPE_CFF = 14
TYPE_DOD = 15
TYPE_MILK = 16
TYPE_OLD = 17
TYPE_MF = 18
TYPE_MM = 19
TYPE_RF = 20
TYPE_SG = 21
TYPE_FC = 22

card_id_to_type_map = {
    CF_FIRST: TYPE_CF,
    CF_2: TYPE_CF,
    CF_3: TYPE_CF,
    DH_FIRST: TYPE_DH,
    DH_2: TYPE_DH,
    DH_3: TYPE_DH,
    DH_4: TYPE_DH,
    DH_5: TYPE_DH,
    DH_6: TYPE_DH,
    ECL_FIRST: TYPE_ECL,
    ECL_2: TYPE_ECL,
    ECL_3: TYPE_ECL,
    GZ_FIRST: TYPE_GZ,
    GZ_2: TYPE_GZ,
    GZ_3: TYPE_GZ,
    GZ_4: TYPE_GZ,
    GZ_5: TYPE_GZ,
    JF_FIRST: TYPE_JF,
    JF_2: TYPE_JF,
    JF_3: TYPE_JF,
    JF_4: TYPE_JF,
    JF_5: TYPE_JF,
    JF_6: TYPE_JF,
    MB_FIRST: TYPE_MB,
    MB_2: TYPE_MB,
    P_FIRST: TYPE_P,
    P_2: TYPE_P,
    P_3: TYPE_P,
    P_4: TYPE_P,
    P_5: TYPE_P,
    P_6: TYPE_P,
    P_7: TYPE_P,
    POW_FIRST: TYPE_POW,
    POW_2: TYPE_POW,
    POW_3: TYPE_POW,
    POW_4: TYPE_POW,
    BC_FIRST: TYPE_BC,
    BC_2: TYPE_BC,
    BC_3: TYPE_BC,
    BC_4: TYPE_BC,
    BC_5: TYPE_BC,
    BC_6: TYPE_BC,
    DC_FIRST: TYPE_DC,
    DC_2: TYPE_DC,
    RV_FIRST: TYPE_RV,
    RV_2: TYPE_RV,
    SPR_FIRST: TYPE_SPR,
    SPR_2: TYPE_SPR,
    BEAR_FIRST: TYPE_BEAR,
    BEAR_2: TYPE_BEAR,
    CT_FIRST: TYPE_CT,
    CT_2: TYPE_CT,
    CFF_FIRST: TYPE_CFF,
    CFF_2: TYPE_CFF,
    DOD_FIRST: TYPE_DOD,
    MILK_FIRST: TYPE_MILK,
    OLD_FIRST: TYPE_OLD,
    OLD_2: TYPE_OLD,
    MF_FIRST: TYPE_MF,
    MF_2: TYPE_MF,
    MM_FIRST: TYPE_MM,
    MM_2: TYPE_MM,
    RF_FIRST: TYPE_RF,
    RF_2: TYPE_RF,
    SG_FIRST: TYPE_SG,
    SG_2: TYPE_SG,
    FC_FIRST: TYPE_FC,
    FC_2: TYPE_FC,
    FC_3: TYPE_FC,
    FC_4: TYPE_FC
}

def get_card_type_for_id(card_id):
    return card_id_to_type_map[card_id]
